runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: 
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: uploader
  DB_USERNAME: root
  DB_SOCKET: "localhost"

handlers:
    - url: /(.*\.(gif|png|jpg|css|js|woff|woff2|ttf))$
      static_files: public/\1
      upload: public/.*\.(gif|png|jpg|css|js|woff|woff2|ttf)$

    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto